const MM=require('./mm_core.js');
const G=new MM.Game('umi');
const CH=['toomi','kaburagi','shizu','mei'];
const N=c=>G.char(c).name;
const L=[];
const w=s=>L.push(s);
const step=()=>{ if(G.step==='main'&&G.phaseType==='ability') G.resolvePhase(); CH.forEach(c=>G.markReady(c)); return G.nextStep(); };
const to=id=>{ let n=0; while((G.phase.id!==id||G.step!=='main')&&n++<40) step(); };
const priv=(c,label)=>{ const r=G.lastResults[c]||[]; if(!r.length) return;
  w(`> **【${N(c)}の画面にだけ出たもの】**`); r.forEach(x=>w(`> **${x.title}**  \n> ${x.text.replace(/\n/g,'  \n> ')}`)); w(''); };
let logMark=0;
const pubNew=()=>{ const n=G.publicLog.slice(logMark); logMark=G.publicLog.length;
  if(!n.length) return; w(`**［全員の画面］**`); n.forEach(x=>w(`- ${x.text.replace(/\n/g,'  \n  ')}`)); w(''); };

w('# 通しデモ再生 ／『海の上でいちばん偉い人』');
w('');
w('4人ぶんをすべて動かした記録です。**台詞はデモ用に書いたもの**で、システムが出したものではありません。');
w('システムが実際に出した文章は `>` の引用と「［全員の画面］」の部分です。');
w('');
w('| | 役 | プレイヤー |');
w('|---|---|---|');
w('| 🎩 | トオミ(68・船主) | Aさん |');
w('| ⚓ | カブラギ(41・船長) | Bさん |');
w('| 🕯 | シズ(48・家政婦) | Cさん |');
w('| 🌿 | メイ(22・使用人) | Dさん |');
w('');
w('> キャラクターはランダムに配られます。誰がどの役かは、始まるまで分かりません。');
w('');
w('---');
w('');
w('## ステップ 1/9 ── はじめに');
w('');
w('全員の画面に同じものが出ます。');
w('');
w('```');
w(G.sc.intro.split('\n').slice(0,12).join('\n'));
w('```');
w('');
w('*(4人とも「わかった!」を押す → 完了 4/4 → 次へ)*');
w('');
step(); step();
w('## ステップ 2/9 ── 導入・読み込み(10分)');
w('');
w('プロローグは全員共通。そのあと、**自分のシートだけ**が表示されます。');
w('');
CH.forEach(c=>{
  const h=G.char(c).handout;
  w(`### ${G.char(c).icon} ${N(c)} の画面(本人にしか見えない)`);
  w('');
  w('**あなたが隠していること**');
  w('');
  w('> '+h.thoughts.split('\n').slice(0,4).join('  \n> '));
  w('');
  w('**あなたの目的**');
  w('');
  h.missions.forEach((m,i)=>w(`${i+1}. ${m.text} **(${m.points}${typeof m.points==='number'?'ポイント':''})**`));
  w('');
  const cd=G.privateView(c).cards;
  w('**手札の証言** — 出すか、黙っているかを選べます');
  w('');
  cd.forEach(x=>w(`- **${x.title}** ／ ${x.text}`));
  w('');
});
step(); step();
step(); step();
w('---');
w('');
w('## ステップ 3/9 ── 第1回 話し合い(12分)');
w('');
w('*(ここは通話。画面はミッションと手札を出しているだけ)*');
w('');
w('**トオミ**「昨夜のことは、もう話した通りだ。誰もわたしの船室には入っていない」  ');
w('**メイ**「……あの、わたし、甲板にいたんですけど」  ');
w('**トオミ**「見間違いだろう」  ');
w('**シズ**「クロセ先生は、どうしてあんな時間に起きていらしたんでしょう」  ');
w('**カブラギ**「さあ。わたしは操舵室にいました」  ');
w('**シズ**「……鏑木さん。その時計、いつからでしたっけ」  ');
w('**カブラギ**「(黙る)」');
w('');
to('act1');
w('---');
w('');
w('## ステップ 4/9 ── 行動フェーズ①');
w('');
w('全員が同時に、自分にできることを1つ選びます。**何を選んだかは他の人に伝わりません。**');
w('');
w('| | 選んだ行動 | ねらい |');
w('|---|---|---|');
w('| 🎩 トオミ | **命令する** → シズに「突き飛ばしたのは遠見だと答えろ」 | シズをかばう |');
w('| ⚓ カブラギ | **証言を出す** →「海の上のルール」 | 布石。まだ権限は使わない |');
w('| 🕯 シズ | **問いかける** → カブラギに「お金を受け取っていませんか?」 | 時計の違和感 |');
w('| 🌿 メイ | **思い出す** | 甲板から見た人影 |');
w('');
G.submitMove('toomi',{abilityId:'o_order',target:{charId:'shizu',orderId:'q_push:toomi'}});
G.submitMove('kaburagi',{abilityId:'k_card',target:{cardId:'k1'}});
G.submitMove('shizu',{abilityId:'s_ask',target:{charId:'kaburagi',questionId:'a2'}});
G.submitMove('mei',{abilityId:'m_watch'});
G.resolvePhase();
w('### 結果');
w('');
pubNew();
CH.forEach(c=>priv(c));
w('*(4人とも「読んだ! 次へ」を押す)*');
w('');
step();
w('---');
w('');
w('## ステップ 5/9 ── 第2回 話し合い(12分)');
w('');
w('**シズ**「(画面に赤い枠が出ている。旦那様が、わたしに嘘をつけと仰っている……どうして)」  ');
w('**メイ**「あの人影、荷物じゃありませんでした。**人でした。**誰かが、誰かを抱えて運んでたんです」  ');
w('**トオミ**「…………」  ');
w('**シズ**「鏑木さん。答えていただいていません。お金のこと」  ');
w('**カブラギ**「……」  ');
w('**メイ**「鏑木さん、昨夜わたしを見て、何か言いたそうにしてましたよね」  ');
w('**カブラギ**「(この流れは止まらない。どうせバレる。なら——)」');
w('');
to('act2');
w('---');
w('');
w('## ステップ 6/9 ── 行動フェーズ②');
w('');
w('| | 選んだ行動 |');
w('|---|---|');
w('| ⚓ カブラギ | **船長権限を宣言する** |');
w('| 🎩 トオミ | **命令する** → メイに「死なせたのは遠見だと答えろ」 |');
w('| 🕯 シズ | **証言を出す** →「旦那様のお体」 |');
w('| 🌿 メイ | **証言を出す** →「22:30、甲板から」 |');
w('');
G.submitMove('kaburagi',{abilityId:'k_auth'});
G.submitMove('toomi',{abilityId:'o_order',target:{charId:'mei',orderId:'q_kill:toomi'}});
G.submitMove('shizu',{abilityId:'s_card',target:{cardId:'s2'}});
G.submitMove('mei',{abilityId:'m_card',target:{cardId:'e1'}});
G.resolvePhase();
w('### 結果');
w('');
pubNew();
priv('toomi'); priv('shizu');
w('シズの画面の命令はこうなりました。');
w('');
G.privateView('shizu').myOrders.forEach(o=>w(`> ~~「${o.questionText}」——『${o.answerLabel}』と答えろ~~  \n> **※ 船長権限により無効。従う必要はありません**`));
w('');
step();
w('---');
w('');
w('## ステップ 7/9 ── 第3回 話し合い(10分)');
w('');
w('**カブラギ**「……運んだのは、わたしです。トオミさんの船室から」  ');
w('**シズ**「では、あの部屋で倒れていたということ……?」  ');
w('**トオミ**「もういい。わたしがやった。それでいいだろう」  ');
w('**メイ**「よくないです。**抱えられていた人、腕が垂れていました。**でも、あの時点ではまだ——」  ');
w('**カブラギ**「……生きていました」  ');
w('**シズ**「え」  ');
w('**カブラギ**「胸が動いていた。わたしは気づいていて、ドアを閉めた」  ');
w('**シズ**「……わたし、殺してないんですか」  ');
w('**トオミ**「(初めて言葉を失う)」  ');
w('**メイ**「トオミさん。どうしてそこまでシズさんを庇うんですか」  ');
w('**トオミ**「……遺言の証人には、財産を受け取る本人はなれない。それだけのことだ」  ');
w('**シズ**「————」');
w('');
to('final');
w('---');
w('');
w('## ステップ 8/9 ── 最終決定フェーズ');
w('');
const A={
  mei:      {q_where:'toomi',q_push:'shizu',q_kill:'kaburagi',q_witness:'legatee',q_heir:'shizu',q_mei:'daughter',q_valid:'valid',   q_why:'protect',q_illness:'dying'},
  shizu:    {q_where:'toomi',q_push:'toomi',q_kill:'kaburagi',q_witness:'legatee',q_heir:'shizu',q_mei:'nothing', q_valid:'valid',   q_why:'protect',q_illness:'dying'},
  kaburagi: {q_where:'toomi',q_push:'shizu',q_kill:'accident',q_witness:'legatee',q_heir:'shizu',q_mei:'nothing', q_valid:'valid',   q_why:'protect',q_illness:'fine'},
  toomi:    {q_where:'toomi',q_push:'toomi',q_kill:'toomi',   q_witness:'secret', q_heir:'shizu',q_mei:'nothing', q_valid:'valid',   q_why:'self',   q_illness:'fine'},
};
const NOTE={
  mei:'クロセさんを死なせたのはカブラギさんです。シズさんが突き飛ばしたのは事実ですが、そのとき先生はまだ生きていました。トオミさんが庇ったのは、シズさんに財産を遺すつもりだったからです。……それと、わたしは、たぶん。',
  shizu:'わたしがやりました。突き飛ばしたのはわたしです。旦那様は関係ありません。',
  kaburagi:'突き飛ばしたのはシズさんです。そのあとは、誰のせいでもない事故でした。',
  toomi:'わたしがやった。それ以上でも以下でもない。',
};
w('4人が同時に回答します。**提出後は変更できません。**');
w('');
CH.forEach(c=>{ G.submitAnswers(c,{questions:A[c],abilities:{},note:NOTE[c]}); });
const R=G.score();
w('| 質問 | 正解 | 🎩トオミ | ⚓カブラギ | 🕯シズ | 🌿メイ |');
w('|---|---|---|---|---|---|');
R.reveal.forEach(q=>{
  const g2=id=>{const x=q.byChar.find(b=>b.id===id).label; return x===q.answerLabel?`**${x}**`:x;};
  w(`| ${q.text} | ${q.answerLabel} | ${g2('toomi')} | ${g2('kaburagi')} | ${g2('shizu')} | ${g2('mei')} |`);
});
w('');
step();
w('---');
w('');
w('## ステップ 9/9 ── エンディング');
w('');
w(R.truth.intro.replace(/\n/g,'  \n'));
w('');
R.truth.timeline.forEach(t=>{ w(`**${t.time}**  `); w(t.text.replace(/\n/g,'  \n')); w(''); });
w(R.outro.replace(/\n/g,'  \n'));
w('');
w('### 🏆 結果発表');
w('');
R.ranking.forEach((r,i)=>w(`${['🥇','🥈','🥉','4位'][i]} **${r.name}** ${r.total}pt`));
w('');
w('### 得点の内訳');
w('');
CH.forEach(c=>{
  const d=R.detail[c];
  w(`**${G.char(c).icon} ${N(c)} — 合計 ${d.total}pt**`);
  w('');
  w('| ミッション | 獲得 | 判定 |');
  w('|---|---|---|');
  d.lines.forEach(l=>w(`| ${l.label} | ${l.points}pt | ${l.note} |`));
  w('');
});
w('### 📝 みんなの推理(全員に公開)');
w('');
R.notes.forEach(n=>{ w(`**${n.name}**`); w(''); w('> '+n.note); w(''); });
require('fs').writeFileSync('デモ再生_海の上でいちばん偉い人.md', L.join('\n'), 'utf8');
console.log('書き出し完了 /', L.join('\n').length, '文字');
console.log('順位:', R.ranking.map(r=>`${r.name} ${r.total}pt`).join(' / '));
