const io = require('socket.io-client');
const URL='http://localhost:3111'; const mk=()=>io(URL,{transports:['websocket']});
const P=(s,e,a)=>new Promise(r=>s.emit(e,a,r)); const wait=ms=>new Promise(r=>setTimeout(r,ms));
const S={};
(async()=>{
  const A=mk(),B=mk(),C=mk();
  [['A',A],['B',B],['C',C]].forEach(([k,s])=>s.on('mm:state',st=>S[k]=st));
  await wait(400);
  const {code}=await P(A,'mm:create',{name:'あらい',scenarioId:'cake'});
  await P(B,'mm:join',{code,name:'びー'}); await P(C,'mm:join',{code,name:'しー'});
  await P(A,'mm:toSelect',{}); await wait(150);
  await P(A,'mm:pick',{charId:'natsuki'}); await P(B,'mm:pick',{charId:'ryusei'}); await P(C,'mm:pick',{charId:'kaito'});
  await P(A,'mm:start',{}); await wait(200);
  console.log('カイトの既知キーワード:', S.C.priv.known.map(k=>`${k.charName}=${k.keyword}`).join(', '));
  await P(A,'mm:next',{}); await wait(150); await P(A,'mm:next',{}); await wait(150);
  console.log('フェーズ:', S.A.pub.phase.title, '/ 場所数', S.A.pub.scenario.places.length);
  const revA=[]; A.on('mm:reveal',d=>revA.push(...d.results));
  const revB=[]; B.on('mm:reveal',d=>revB.push(...d.results));
  console.log('A(ナツキ) リュウセイの部屋を調査:', await P(A,'mm:act',{placeId:'r_ryusei'}));
  console.log('B(リュウセイ) 自室で水:', await P(B,'mm:act',{placeId:'r_ryusei',abilityId:'r1'}));
  console.log('C(カイト) 自室のドアを閉める:', await P(C,'mm:act',{placeId:'living',abilityId:'k1',target:{doorId:'r_kaito'}}));
  await wait(1200);
  console.log('--- ナツキが得たもの ---'); revA.forEach(r=>console.log(' ・',r.title,'|',r.text.replace(/\n/g,' ').slice(0,70)));
  console.log('--- リュウセイが得たもの ---'); revB.forEach(r=>console.log(' ・',r.title,'|',r.text.replace(/\n/g,' ').slice(0,70)));
  console.log('共有ボード:', JSON.stringify(S.A.pub.board.doors), 'log最新:', S.A.pub.board.log.slice(-2).map(x=>x.text).join(' / '));
  // 次フェーズ: ナツキが閉じたカイトの部屋にすり抜け
  await P(A,'mm:next',{}); await wait(200);
  console.log('フェーズ:', S.A.pub.phase.title);
  revA.length=0;
  console.log('A: キッチン調査＋すり抜けでカイトの部屋へ:', await P(A,'mm:act',{placeId:'kitchen',extra:'action',abilityId:'n1',target:{placeId:'r_kaito'}}));
  await P(B,'mm:act',{placeId:'r_kaito'});
  await P(C,'mm:act',{placeId:'toilet'});
  await wait(1200);
  console.log('--- ナツキ ---'); revA.forEach(r=>console.log(' ・',r.title,'|',r.text.replace(/\n/g,' ').slice(0,80)));
  console.log('冷蔵庫電源:', S.A.pub.board.fridgePower);
  while(S.A.pub.phase.type!=='final'){ await P(A,'mm:next',{}); await wait(200); }
  const q={q_eater:'ryusei',q_fake:'kaito',q_taste:'a',q_jewel:'a',q_fail:'a',q_sound1:'a',q_sound2:'a'};
  await P(A,'mm:answers',{questions:q,abilities:{ryusei:['r1','r2','r3'],kaito:['k1','k2','k3']},note:'リュウセイが偽物とすり替えた'});
  await P(B,'mm:answers',{questions:q,abilities:{},note:''});
  await P(C,'mm:answers',{questions:q,abilities:{},note:''});
  await wait(1200);
  console.log('結果:', S.A.pub.result.ranking.map(r=>`${r.name} ${r.total}pt`).join(' / '));
  A.close();B.close();C.close();process.exit(0);
})().catch(e=>{console.error('ERR',e);process.exit(1)});
