const io=require('socket.io-client');const URL='http://localhost:3112';
const mk=()=>io(URL,{transports:['websocket']});const P=(s,e,a)=>new Promise(r=>s.emit(e,a,r));
const wait=ms=>new Promise(r=>setTimeout(r,ms));const S={};
(async()=>{
  const A=mk(),B=mk(),C=mk(),D=mk();const CL={A,B,C,D};
  Object.entries(CL).forEach(([k,s])=>s.on('mm:state',st=>S[k]=st));
  await wait(500);
  const cat0=await P(A,'mm:scenarios',{});
  console.log('入口の作品一覧:',cat0.list.map(x=>`${x.title}(${x.players.min}人)`).join(' / '));
  const {code}=await P(A,'mm:create',{name:'あらい'});
  await wait(250);
  console.log('部屋を作った:',code,'/ シナリオ:',S.A.lobby.scenarioId===null?'まだ未定 ✅':'!!');
  const show=()=>S.A.lobby.catalog.map(c=>`${c.title}:${c.playable?'選べる':'✗'+(c.need||'')}`).join(' | ');
  console.log('1人 →',show());
  await P(B,'mm:join',{code,name:'びー'}); await wait(150);
  console.log('2人 →',show());
  await P(C,'mm:join',{code,name:'しー'}); await wait(150);
  console.log('3人 →',show());
  console.log('  3人で4人用を選ぼうとする:',(await P(A,'mm:pickScenario',{scenarioId:'umi'})).msg);
  console.log('  3人でケーキを選ぶ:',(await P(A,'mm:pickScenario',{scenarioId:'cake'})).ok);
  console.log('  ホスト以外が選ぼうとする:',(await P(B,'mm:pickScenario',{scenarioId:'cake'})).msg);
  await P(D,'mm:join',{code,name:'でぃー'}); await wait(150);
  console.log('4人 →',show());
  console.log('  4人で海の上を選ぶ:',(await P(A,'mm:pickScenario',{scenarioId:'umi'})).ok);
  await wait(150);
  await wait(200);
  console.log('  選択中:',S.A.lobby.scenarioId,'／ 全員の画面に反映:',S.D.lobby.scenarioId);
  console.log('  開始:',(await P(A,'mm:start',{})).ok);
  await wait(250);
  console.log('  配られた役:',Object.keys(CL).map(k=>`${k}=${S[k].priv.character.name}`).join(' / '));
  console.log('  最初のステップ:',S.A.pub.phase.title,'/',S.A.pub.step);
  Object.values(CL).forEach(c=>c.close());process.exit(0);
})().catch(e=>{console.error('ERR',e.message);process.exit(1)});
